const WORDS_EASY = ['the','be','to','of','and','a','in','that','have','it','for','not','on','with','he','as','you','do','at','this','but','his','by','from','they','we','her','she','or','an','will','my','one','all','would','there','their','what','so','up','out','if','about','who','get','which','go','me','when','make','can','like','time','no','just','him','know','take','people','into','year','your','good','some','could','them','see','other','than','then','now','look','only','come','its','over','think','also','back','after','use','two','how','our','work','first','well','way','even','new','want','because','any','these','give','day','most','us'];
const WORDS_MEDIUM = ['ability','absolute','academic','accept','achieve','acquire','actually','additional','address','adequate','adjust','administration','advantage','affect','afford','agency','agreement','alternative','analysis','ancient','announce','annual','anxiety','apparent','application','appreciate','appropriate','approve','argument','arrangement','assessment','assignment','assistance','associate','assumption','atmosphere','attachment','attempt','attitude','attribute','authority','automatic','available','awareness','background','balance','barrier','basically','battery','beginning','behavior','belief','beneath','benefit','besides','biological','boundary','brilliant','broadcast','budget','cabinet','calculate','campaign','candidate','capable','capacity','capture','career','category','celebrate','challenge','champion','character','chemical','childhood','circumstance','civilian','classical','climate','clinical','cognitive','colleague','colonial','combination','comfortable','command','commercial','commission','commitment','committee','communicate','community','comparison','compensation','competition','complaint','complement','complexity','component','comprehensive','concentrate','concept','conclusion','condition','conduct','conference','confidence','confirm','conflict','confusion','connection','conscious','consequence','conservation','considerable','consistent','constantly','constitution','construction','consultant','consumer','contemporary','content','context','contract','contrast','contribute','controversy','convention','conversation','convert','convince','cooperation','coordinate','corporate','correspond','coverage','creation','creative','criminal','criteria','critical','criticism','cultural','currency','currently','curriculum'];
const WORDS_HARD = ['acknowledge','acquisition','administration','advertisement','approximately','architecture','characteristic','circumstances','collaboration','communication','comprehensive','concentration','configuration','consciousness','consideration','constitutional','contemporary','contradiction','controversial','correspondence','demonstration','determination','discrimination','electromagnetic','encouragement','entertainment','environmental','establishment','experimentation','extraordinary','fundamentally','generalization','identification','implementation','impressionable','inadvertently','inappropriate','independently','infrastructure','interpretation','investigation','justification','knowledgeable','manufacturing','Mediterranean','miscellaneous','misunderstand','neighbourhood','notwithstanding','organizational','overwhelmingly','pharmaceutical','photosynthesis','predominantly','professionalism','proportionate','psychologically','questionnaire','recommendation','reconnaissance','representation','responsibility','revolutionary','simultaneously','sophistication','specifications','straightforward','superintendent','transformation','transportation','uncomfortable','understandable','unfortunately','unprecedented','vulnerability'];
const LESSONS = [
  {id:1,title:'Home Row Basics',desc:'Learn the foundation keys: A S D F J K L ;',keys:['a','s','d','f','j','k','l',';'],text:'asdf jkl; asdf jkl; fads lk;j fjdk sl;a asd; fkjl asdf jkl; fjdk sala daks fljk asdf jkl; asd; fkjl sala daks'},
  {id:2,title:'Home Row Words',desc:'Type simple words using home row keys',keys:['a','s','d','f','j','k','l',';'],text:'ads all fall flask salad dad lads fads ask add sad lad fall dad ask ads salad flask lads fads all add sad lad'},
  {id:3,title:'E and I Keys',desc:'Add E and I to your skills',keys:['e','i'],text:'die fie lie side file like did life idea field aside slide file die side like life idea field aside slide did fie lie'},
  {id:4,title:'R and U Keys',desc:'Reach for R and U keys',keys:['r','u'],text:'rule fur sure fire ride rude lure pure raise rural future rule fur sure fire ride rude lure pure raise rural future'},
  {id:5,title:'T and Y Keys',desc:'Master T and Y with index fingers',keys:['t','y'],text:'the yet try style kitty dirty dusty rusty they dusty style try yet the kitty dirty rusty they dusty style try yet'},
  {id:6,title:'Top Row Complete',desc:'Practice all top row keys together',keys:['q','w','e','r','t','y','u','i','o','p'],text:'write your power quote quiet type equip trip wire require write your power quote quiet type equip trip wire require'},
  {id:7,title:'G and H Keys',desc:'Stretch to G and H center keys',keys:['g','h'],text:'high gash huge flag hang gush sigh ghast eight height fight light high gash huge flag hang gush sigh ghast fight'},
  {id:8,title:'Bottom Row: Z X C V',desc:'Left hand bottom row keys',keys:['z','x','c','v'],text:'voice exact cave vice size zinc fix civil vivid freeze voice exact cave vice size zinc fix civil vivid freeze cave'},
  {id:9,title:'Bottom Row: B N M',desc:'Right hand bottom row keys',keys:['b','n','m'],text:'name barn mean number mine born beam number mine barn name mean born beam number mine barn name mean born beam'},
  {id:10,title:'Numbers Row',desc:'Learn to type numbers 1-0',keys:['1','2','3','4','5','6','7','8','9','0'],text:'10 29 38 47 56 192 837 465 10 29 38 47 56 192 837 465 102 394 857 603 102 394 857 603 10 29 38 47 56'},
  {id:11,title:'Common Punctuation',desc:'Period comma and basic punctuation',keys:[',','.','/','\''],text:"it's fine, really. yes/no. don't stop, keep going. he's here, she's there. let's go. it's fine, really."},
  {id:12,title:'Full Review',desc:'Practice everything you have learned',keys:[],text:'The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs. How vexingly quick daft zebras jump.'}
];
const QUOTES = [
  "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.",
  "In the middle of every difficulty lies opportunity. The important thing is not to stop questioning.",
  "Life is what happens when you're busy making other plans. Imagine all the people living life in peace.",
  "The future belongs to those who believe in the beauty of their dreams. Keep your face toward the sunshine.",
  "It does not matter how slowly you go as long as you do not stop. Our greatest glory is not in never falling.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Be yourself; everyone else is already taken. To live is the rarest thing; most people just exist.",
  "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.",
  "You miss one hundred percent of the shots you don't take. The best time to plant a tree was twenty years ago.",
  "The only impossible journey is the one you never begin. Believe you can and you're halfway there."
];
const CODE_SNIPPETS = [
  'function fibonacci(n) {\n  if (n <= 1) return n;\n  return fibonacci(n - 1) + fibonacci(n - 2);\n}',
  'const sum = (arr) => arr.reduce((a, b) => a + b, 0);',
  'for (let i = 0; i < items.length; i++) {\n  console.log(items[i]);\n}',
  'class Stack {\n  constructor() { this.items = []; }\n  push(val) { this.items.push(val); }\n  pop() { return this.items.pop(); }\n}',
  'const filtered = data.filter(item => item.active).map(item => item.name);'
];
const PARAGRAPHS = [
  "Technology has transformed the way we live and work in profound ways. From smartphones that connect us instantly to artificial intelligence that can process vast amounts of data, the digital revolution continues to reshape every aspect of modern life. As we move forward, the challenge lies in harnessing these powerful tools responsibly while ensuring that the benefits are shared widely across society.",
  "The art of writing is the art of discovering what you believe. Every sentence is a journey of exploration, each word carefully chosen to convey meaning and emotion. Good writing requires patience, practice, and a willingness to revise and refine until the message shines through with clarity and purpose. The best writers are those who never stop learning and growing in their craft.",
  "Nature has an incredible ability to heal and restore itself when given the chance. Forests regenerate, rivers clean themselves, and ecosystems find new balance after disturbances. This resilience teaches us important lessons about adaptation and recovery. By protecting natural spaces and reducing our environmental impact, we can help ensure that future generations inherit a healthy and vibrant planet."
];
const KB_LAYOUT = [
  [{k:'`',c:'lp'},{k:'1',c:'lp'},{k:'2',c:'lr'},{k:'3',c:'lm'},{k:'4',c:'li'},{k:'5',c:'li'},{k:'6',c:'ri'},{k:'7',c:'ri'},{k:'8',c:'rm'},{k:'9',c:'rr'},{k:'0',c:'rp'},{k:'-',c:'rp'},{k:'=',c:'rp'},{k:'Backspace',c:'rp',l:'⌫'}],
  [{k:'Tab',c:'lp',l:'Tab'},{k:'q',c:'lp'},{k:'w',c:'lr'},{k:'e',c:'lm'},{k:'r',c:'li'},{k:'t',c:'li'},{k:'y',c:'ri'},{k:'u',c:'ri'},{k:'i',c:'rm'},{k:'o',c:'rr'},{k:'p',c:'rp'},{k:'[',c:'rp'},{k:']',c:'rp'},{k:'\\',c:'rp'}],
  [{k:'CapsLock',c:'lp',l:'Caps'},{k:'a',c:'lp'},{k:'s',c:'lr'},{k:'d',c:'lm'},{k:'f',c:'li'},{k:'g',c:'li'},{k:'h',c:'ri'},{k:'j',c:'ri'},{k:'k',c:'rm'},{k:'l',c:'rr'},{k:';',c:'rp'},{k:"'",c:'rp'},{k:'Enter',c:'rp',l:'Enter'}],
  [{k:'ShiftLeft',c:'lp',l:'Shift'},{k:'z',c:'lp'},{k:'x',c:'lr'},{k:'c',c:'lm'},{k:'v',c:'li'},{k:'b',c:'li'},{k:'n',c:'ri'},{k:'m',c:'ri'},{k:',',c:'rm'},{k:'.',c:'rr'},{k:'/',c:'rp'},{k:'ShiftRight',c:'rp',l:'Shift'}],
  [{k:'Space',c:'thumb',l:'Space'}]
];
